import {
  Archive, ArrowClockwise, ArrowDown, ArrowLeft, ArrowRight, ArrowSquareOut,
  ArrowUp, Bank, Bell, BookOpen, BowlFood, Brain, Briefcase, Buildings, CalendarBlank,
  Calculator, Camera, CaretDown, CaretLeft, CaretRight, ChartDonut, ChartLineUp, ChatTeardropText, Check,
  CheckCircle, CheckSquare, Clock, Cloud, Coffee, Copy, CreditCard, Crown, CurrencyCircleDollar,
  DeviceMobile, DotsThree, DotsSixVertical, DownloadSimple, Egg, Envelope, Eye, EyeSlash, FileText,
  FilmSlate, Fire, FirstAid, FloppyDisk, FolderOpen, Funnel, GameController, GasPump,
  GearSix, Gift, GoogleLogo, GraduationCap, HandCoins, HardDrives, Heart, House, IdentificationCard, Image, Key,
  Headphones, Highlighter, Infinity as InfinityIcon, Keyboard, Lightbulb, Link, List, ListBullets, ListChecks, ListNumbers, LockKey, MagnifyingGlass, MapPin, Megaphone,
  Lightning, Microphone, Minus, Money, Moon, MusicNote, NotePencil, Package, PaperPlaneTilt,
  Paragraph, Pause, PencilSimple, PiggyBank, Plant, Play, Plus, PlusCircle, PushPin, Question, Quotes, Receipt, Rocket,
  Scissors, ShoppingBag, SignOut, SkipForward, Sparkle, Square, SquaresFour, Star, Sun, Sword, Table, Tag, TextHOne, TextHThree, TextHTwo, Timer, Trash,
  Robot, Tray, TrayArrowDown, TreeStructure, TrendUp, Trophy, UploadSimple, User, Users, VideoCamera,
  Wallet, Warning, WifiHigh, X, Database, Certificate,
} from '@phosphor-icons/react';

const ICONS = {
  archive: Archive,
  back: ArrowLeft,
  bank: Bank,
  bell: Bell,
  book: BookOpen,
  bowlFood: BowlFood,
  brain: Brain,
  briefcase: Briefcase,
  buildings: Buildings,
  calendar: CalendarBlank,
  calculator: Calculator,
  camera: Camera,
  caretDown: CaretDown,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  chartDonut: ChartDonut,
  chartLine: ChartLineUp,
  quote: ChatTeardropText,
  check: Check,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  copy: Copy,
  creditCard: CreditCard,
  crown: Crown,
  currency: CurrencyCircleDollar,
  deviceMobile: DeviceMobile,
  dots: DotsThree,
  dotsSix: DotsSixVertical,   // grip kéo thả — affordance chuẩn, không dùng cho menu
  download: DownloadSimple,
  egg: Egg,
  envelope: Envelope,
  external: ArrowSquareOut,
  eye: Eye,
  eyeOff: EyeSlash,
  file: FileText,
  film: FilmSlate,
  fire: Fire,
  firstAid: FirstAid,
  folder: FolderOpen,
  funnel: Funnel,
  game: GameController,
  gas: GasPump,
  gear: GearSix,
  gift: Gift,
  google: GoogleLogo,
  graduation: GraduationCap,
  handCoins: HandCoins,
  heart: Heart,
  headphones: Headphones,
  highlighter: Highlighter,
  house: House,
  identification: IdentificationCard,
  image: Image,
  inbox: Tray,
  infinity: InfinityIcon,
  key: Key,
  keyboard: Keyboard,
  lightbulb: Lightbulb,
  lightning: Lightning,
  link: Link,
  list: List,
  listBullets: ListBullets,
  listChecks: ListChecks,
  listNumbers: ListNumbers,
  lock: LockKey,
  mapPin: MapPin,
  megaphone: Megaphone,
  microphone: Microphone,
  minus: Minus,
  money: Money,
  cash: Money,
  moon: Moon,
  music: MusicNote,
  note: NotePencil,
  package: Package,
  paragraph: Paragraph,
  paperPlane: PaperPlaneTilt,
  pause: Pause,
  pencil: PencilSimple,
  piggyBank: PiggyBank,
  plant: Plant,
  play: Play,
  plus: Plus,
  plusCircle: PlusCircle,
  pushPin: PushPin,
  question: Question,
  quotes: Quotes,
  receipt: Receipt,
  refresh: ArrowClockwise,
  arrowsClockwise: ArrowClockwise,
  rocket: Rocket,
  robot: Robot,
  save: FloppyDisk,
  scissors: Scissors,
  search: MagnifyingGlass,
  server: HardDrives,
  shopping: ShoppingBag,
  signOut: SignOut,
  skip: SkipForward,
  sparkle: Sparkle,
  square: Square,
  squares: SquaresFour,
  star: Star,
  sun: Sun,
  sword: Sword,
  table: Table,
  tag: Tag,
  textH1: TextHOne,
  textH2: TextHTwo,
  textH3: TextHThree,
  timer: Timer,
  trash: Trash,
  tray: TrayArrowDown,
  tree: TreeStructure,
  trend: TrendUp,
  trophy: Trophy,
  upload: UploadSimple,
  user: User,
  users: Users,
  video: VideoCamera,
  wallet: Wallet,
  warning: Warning,
  wifi: WifiHigh,
  database: Database,
  certificate: Certificate,
  x: X,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  arrowRight: ArrowRight,
};

const ALIASES = {
  '✅': 'checkCircle', '✔️': 'checkCircle', '⚠️': 'warning', '❌': 'x',
  '📝': 'note', '📌': 'pushPin', '🔗': 'link', '💰': 'money', '💸': 'handCoins',
  '🏦': 'bank', '💳': 'creditCard', '📥': 'inbox', '📤': 'paperPlane', '🗑️': 'trash',
  '🔒': 'lock', '🔔': 'bell', '🎯': 'trend', '✨': 'sparkle', '📅': 'calendar',
  '🔍': 'search', '⚙️': 'gear', '📁': 'folder', '📄': 'file', '🏠': 'house',
};

export default function AppIcon({ name, size = 18, weight = 'regular', ...props }) {
  const Icon = ICONS[ALIASES[name] || name] || Package;
  return <Icon size={size} weight={weight} aria-hidden="true" {...props} />;
}
